### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by dantodor** [BeaconCMS/beacon_demo#11]
I'm trying to evaluate if I can use BeaconCMS, so I tried to run this demo.
Clone, `mix deps.get`, `mix ecto.setup`, `mix phx.server` .

The issue that I'm facing is the it can't found the narwin.webp file, and also getting the same error when trying to upload new media. The error is:
```
KeyError at GET /admin/demo/media_library/upload
key :agent not found in: %{
  socket: #Phoenix.LiveView.Socket< ....
```
The weird thing is that down the page, it really shows that `narwin.webp` was loaded indeed:
```
streams: %{
    assets: %Phoenix.LiveView.LiveStream{
      name: :assets,
      dom_id: #Function<1.120097161/1 in Beacon.LiveAdmin.MediaLibraryLive.Index.mount/3>,
      ref: "0",
      inserts: [
        {"4765ae81-e575-4c24-8813-7a60b093e922-e905343b-ec93-4080-90dd-be0834f40511",
         -1,
         %Beacon.MediaLibrary.Asset{
           __meta__: #Ecto.Schema.Metadata<:loaded, "beacon_assets">,
           id: "e905343b-ec93-4080-90dd-be0834f40511",
           site: :demo,
           file_name: "narwin.webp",
           file_body: <<82, 73, 70, 70, 24, 180, 0, 0, 87, 69, 66, 80, 86, 80,
```
Also, the file is not displayed on the entry page, just a placeholder with error.

What am I doing wrong?

Thanks!

**Comment by leandrocp** [comment]
Hey @dantodor nothing wrong on your side :) Both issues are fixed now on the main branch.

The first one by https://github.com/BeaconCMS/beacon_live_admin/pull/200 and the other by https://github.com/BeaconCMS/beacon_demo/commit/22212414a989d43738ede06d2831f080fc1a0bb2

Thanks!
